//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_FILIPPOV_KR.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILET_PRICE
    {
        public int ID_STRANA { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Kyda { get; set; }
        public string Otkyda { get; set; }
        public string Vrema_otpravki { get; set; }
        public Nullable<int> ID_SOTRUDNIKA { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_BILETA { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual SOTRUDNIKI SOTRUDNIKI { get; set; }
        public virtual STRANA STRANA { get; set; }
    }
}
