//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_FILIPPOV_KR.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KR_FILIPPOVEntities : DbContext
    {
        public KR_FILIPPOVEntities()
            : base("name=KR_FILIPPOVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILET_PRICE> BILET_PRICE { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<SOTRUDNIKI> SOTRUDNIKI { get; set; }
        public virtual DbSet<STRANA> STRANA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
