//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_FILIPPOV_KR.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRANA
    {
        public int ID_STRANA { get; set; }
        public string Name { get; set; }
    
        public virtual BILET_PRICE BILET_PRICE { get; set; }
    }
}
